projects:
  amplify:
    schemaPath: src/graphql/schema.json
    includes:
      - api_thing
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
